platform :ios, '9.0'

source 'https://github.com/zzgo/PrivatePods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'CTMediatorDemo' do
  # ignoring warning from pods
  inhibit_all_warnings!
  #pod 'MBProgressHUD', '~> 0.9'
  #pod 'YYKit'
  pod 'Masonry', '~> 1.0.2'
  # , :path => "../Home_Category"
  pod 'Home_Category'
end
